### ISSUE TITLE
It would be helpful to have an index parameter

### ISSUE THREAD

**Issue by NosillaCast** [Honatas/bootstrap-4-autocomplete#15]
If the user of the plugin creates multiple instances of an input text box with autocomplete, there appears to be no way to tell the callback which instance on which to take action. In my use, I will have an unconstrained number of input text boxes with autocomplete, created as Instances of a Class. Each Instance has a unique index number associated with the enclosing div.

Solution: I'm going to send a pull request to do the following:

I suggest adding an additional option to identify the ID of the parent of the text box.  I added in `opts.onSelectItem`  one line, `parentIDIndex: opts.parentIDIndex`.

Armed with this, I can iterate through my Array for my search box IDs:

```
for (i=1; i < Array.length; i++){
  $(`#${Array[i].searchBoxID}`).autocomplete({
    source: tzNamesObject,
    onSelectItem: onSelectItem,
    highlightTyped: false,
    threshold: 3,
    parentIDIndex: i  
  });
};
```

And then in the `onSelectItem` callback I can set values unique to each ID:
```
function onSelectItem(item){
  Array[item.parentIDIndex].location = `${item.value}`;  
}
```

**Comment by Honatas** [comment]
Hello @NosillaCast.

Thanks for the interest and time spent creating this PR.

Actually though, this is not necessary, since the second parameter to the onSelectItem callback is the text field itself. Something like this:
`
function onSelectItem(item, element) {
  console.log(element.id);
}
`

This would output the id of the textfield on which the event has triggered.

So I'm closing this issue and the PR.
