### ISSUE TITLE
Why is value set to label and not to value?

### ISSUE THREAD

**Issue by Fleshgrinder** [Honatas/bootstrap-4-autocomplete#8]
The default source is `{'label': 'value'}` and my expectation was that I can have a more descriptive label and that the value is inserted as the value. However, [the label is inserted by default](https://github.com/Honatas/bootstrap-4-autocomplete/blob/406299c4baa6fbb06b22c50bbd13edd38ab87934/src/bootstrap-4-autocomplete.ts#L73), which is counter intuitive (at least to me). Any particular reason why this is the case?

**Comment by Honatas** [comment]
Originally there would be no label or value, it was a single information. This isn't efficient when you need more complex sentences (or more descriptive labels as you say). That's why I have come up with a value:label approach. Maybe this is counter intuitive to you because of the key:value notion, where "value" is in the other position when you compare to the value:label notion which is being used here. Maybe I should've named it "id" instead of "value", but it is too late to change it now.

Anyway, philosophies apart, the label is what the user sees, and the value is the id we use underneath. Since the html component is an input tag it can only contain a single information, so the label is what goes there. If you need the value (and most likely you will), you must use the callback function **onSelectItem** to get it.
